
spring:
  config:
    activate:
      on-profile: local
  application:
    name: order

  kafka:
    bootstrap-servers: localhost:9092


  data:
    mongodb:
      authentication-database: admin
      username: user
      password: password
      database: buy01
      port: 27017
      host: localhost
      auto-index-creation: true

stripe:
  api:
    key: 'sk_test_51Qoq2iA0ESShc8j9M2q6RFhfIjoRkJQi0Y4ihwlkx3H7jApJAnPSlfXQIWT7PCVt1tK8HYH4vLV87I7QL3fdOWZK005fdSHG6F'
  webhook:
    secret: ""

server:
  port: 9004
