spring:
  config:
    activate:
      on-profile: local
  application:
    name: gateways
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:39037"
            #              - "https://localhost:4200"
            #              - "localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/user/**
        - id: product
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/product/**
        - id: media
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/media/**
        - id: order
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/order/**
server:
  port: 9000
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.boot.ssl: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web.reactive.cors: DEBUG